version: '2'

services:
  mysqlserver:
    image: mysql
    environment:
      MYSQL_DATABASE: demo
      MYSQL_ROOT_PASSWORD: demo
    volumes:
      - /var/lib/mysql

  song:
    build:
      context: ../.
      dockerfile: docker/app/Dockerfile
      args:
        - userid
    volumes:
      - ../:/srv/app
    environment:
      - DEBUG=1
      - CONFIG_CACHE_ENABLED=0
      - COMPOSER_HOME=/srv/app/.composer
    working_dir: /srv/app
    links:
     - mysqlserver

  song_api:
    build:
      context: ../.
      dockerfile: docker/server/Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ./Song:/srv/app
      - ./docker/server/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - DEBUG=1
      - CONFIG_CACHE_ENABLED=0
      - COMPOSER_HOME=/srv/app/.composer
    working_dir: /srv/app